[package]
name = "kb"
version = "0.1.0"
authors = ["Matt Bettcher <mattbettcher@gmail.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"

[build-dependencies]
lalrpop = "0.19.6"